concurrency:
  cancel-in-progress: false
  group: pages
defaults:
  run:
    shell: bash
jobs:
  build:
    env:
      HUGO_VERSION: 0.115.4
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install OpenJDK 17
      run: sudo apt-get -q install -y openjdk-17-jdk
    - continue-on-error: true
      name: Make 17 the default java version
      run: sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    - continue-on-error: true
      name: Make 17 the default javadoc version
      run: sudo update-alternatives --set javadoc /usr/lib/jvm/java-17-openjdk-amd64/bin/javadoc
    - continue-on-error: true
      name: Print java and javadoc versions
      run: 'echo ''java --version'' && \

        java --version && \

        echo ''javadoc --version'' && \

        javadoc --version && \

        echo ''echo $JAVA_HOME'' && \

        echo $JAVA_HOME

        '
    - continue-on-error: true
      name: Install Hugo CLI
      run: 'wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
        \

        && sudo dpkg -i ${{ runner.temp }}/hugo.deb

        '
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - continue-on-error: true
      name: Build client_java
      run: ./mvnw -B clean install -DskipTests
    - continue-on-error: true
      name: Make Javadoc
      run: ./mvnw -B clean compile javadoc:javadoc javadoc:aggregate
    - continue-on-error: true
      name: Move the Javadoc to docs/static/api/
      run: mv ./target/site/apidocs ./docs/static/api && echo && echo 'ls ./docs/static/api'
        && ls ./docs/static/api
    - continue-on-error: true
      id: pages
      name: Setup Pages
      uses: actions/configure-pages@v3
    - continue-on-error: true
      name: Install Node.js dependencies
      run: '[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true'
      working-directory: ./docs
    - continue-on-error: true
      env:
        HUGO_ENV: production
        HUGO_ENVIRONMENT: production
      name: Build with Hugo
      run: "hugo \\\n  --gc \\\n  --minify \\\n  --baseURL \"${{ steps.pages.outputs.base_url\
        \ }}/\"\n"
      working-directory: ./docs
    - continue-on-error: true
      name: ls ./docs/public/api
      run: echo 'ls ./docs/public/api' && ls ./docs/public/api
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./docs/public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
name: Deploy Documentation to Github Pages
on:
  repository_dispatch:
    types: trigger-ga___github-pages.yaml
permissions:
  contents: read
  id-token: write
  pages: write
